<form method="post" action="<?php echo $block->getPostUrl() ?>">
    
<div class="container">
    <div>
        <label for="first_name"><?= __("First Name") ?></label>
        <p><?php echo $block->getFirstNamee() ?></p>

        <input type="text" name="first_name" disabled/>
    </div>
    <div>
        <label for="last_name"><?= __("Last Name") ?></label>
        <input type="text" name="last_name" data-validate="{required:true}" disabled/>
    </div>
    <div>
        <label for="email"><?= __("Email") ?></label>
        <input type="email" name="email" data-validate="{required:true, 'validate-email':true}" disabled/>
    </div>    
<div>
        <label for="feedback"><?= __("Feedback") ?></label>
        <input type="text" name="feedback" data-validate="{required:true}"/>
    </div>
    <input type="submit" value="<?= __("Submit feedback") ?>" />
    </div>
</form>