
<form action="<?php echo $block->getUrl('dbpatch/index/index'); ?>" method="post">
    <div class="field">
        <label for="firstname">First Name:</label>
        <input type="text" id="firstname" name="firstname" required>
    </div>
    <div class="field">
        <label for="lastname">Last Name:</label>
        <input type="text" id="lastname" name="lastname" required>
    </div>
    <br>
    <div class="actions">
        <button type="submit">Submit</button>
    </div>
</form>
